### PR TITLE
Fix name collision of GHC.TypeLits for base >= 4.11.0

### PR DESCRIPTION
**Pull request by jaccokrijnen**

### CODE REVIEW

**Comment by TikhonJelvis** [comment]
Thanks, this fix looks great! 

I am not sure why Travis is unhappy—I'll try fixing that before merging this PR.

**Comment by khalilfazal** [comment]
I think the error is caused by missing:

```haskell
{-# LANGUAGE CPP #-}
```

because of the use of preprocessors at line 30.

**Comment by jaccokrijnen** [comment]
Ah, I missed the test suite in the .cabal file.

**Comment by TikhonJelvis** [comment]
@khalilfazal That sounds right. I was surprised that the library itself built but the test suite failed.

**Comment by khalilfazal** [comment]
yay! congrats on the build!

**Comment by TikhonJelvis** [comment]
Sweet, looks like it all works. Continuous integration really is pretty awesome.

Thanks for the help!

**Comment by TikhonJelvis** [comment]
Also, just out of curiosity, are you actually using this library for something?

**Comment by jaccokrijnen** [comment]
Indirectly, I was trying to build https://hackage.haskell.org/package/hmt and started investigating from there. Would you be able to publish a new version on Hackage?

**Comment by TikhonJelvis** [comment]
Yes, I can push a new version now.

**Comment by jaccokrijnen** [comment]
Thanks! Happy to have helped.

**Comment by TikhonJelvis** [comment]
Alright, I think I got the upload right. Took me a bit to remember my Hackage password :P.

https://hackage.haskell.org/package/modular-arithmetic-1.2.1.3

**Comment by jaccokrijnen** [comment]
$ cd hmt-0.16
    $ cabal new-build
    ...
    cabal: Failed to build modular-arithmetic-1.2.1.2 (which is required by hmt-0.16). See the build log above for details.
    $ cabal update
    ...
    $ cabal new-build
    ...
    [134 of 134] Compiling Music.Theory.Z12.Drape_1999 ( Music/Theory/Z12/Drape_1999.hs,/home/jacco/projects/hmt-0.16/dist-newstyle/build/x86_64-linux/ghc-8.4.1/hmt-0.16/build/Music/Theory/Z12/Drape_1999.o )
    $

:+1: Thanks

**Pull request merged**
